Fix #77 - Default value for semver
CircleCI-Public/orb-tools-orb pull request #109
Opened 2021-02-14 02:29 UTC by bmbferreira

Adds new parameter to set a default value when the commit
does not contain [semver:<increment_type>] on the subject.

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

### Description

2021-02-14 08:49 UTC, soulfulAdam approved these changes

2021-02-15 02:57 UTC, KyleTryon commented
> I would prefer to fallback to patch if someone forget to add it.
This would result in potentially breaking changes for users of the orb. The design is such that it is on the user merging to specify the update type, otherwise, fail. This may be acceptable for personal use, but would not be adequate for orbs used by many users/teams.

2021-02-15 05:15 UTC, KyleTryon commented
Just having a thought, perhaps we could satisfy all needs by also including a new default of "fail". Any thoughts?

2021-02-15 09:26 UTC, bmbferreira commented
Hi @KyleTryon 

> This would result in potentially breaking changes for users of the orb.
I don't consider this a breaking change since I'm just adding a parameterized fallback value to assume if the user forgets to put the semver thingy on the commit subject. If they don't specify the parameter, it will just have the same behaviour that it had before.

> Just having a thought, perhaps we could satisfy all needs by also including a new default of "fail". Any thoughts?
😕 what's the difference comparing to what I just did?

2021-02-16 11:17 UTC, gmemstr commented
@KyleTryon I think this PR is worthwhile, and I believe, from reviewing the code, it should have the same behaviour that currently exists, as @bmbferreira points out. I won't reopen the PR on your behalf but it may be worth reconsidering :)

2021-02-16 16:29 UTC, KyleTryon commented
@gmemstr @bmbferreira Would love to talk more on this, I have added my comments to the issue here: https://github.com/CircleCI-Public/orb-tools-orb/issues/77#issuecomment-779952494

We will not consider anything here complete or final until the issue is closed and we are all happy 👍

2021-02-16 16:30 UTC, KyleTryon requested changes
Requesting changes only to place this PR on hold and prevent it from accidentally merging until the conversation in the accompanying issue is complete.

My comment: https://github.com/CircleCI-Public/orb-tools-orb/issues/77#issuecomment-779952494

2021-02-16 19:21 UTC, soulfulAdam approved these changes
Requesr cjange

2021-05-06 13:55 UTC, gmemstr commented
Closing this as we're looking at other way of approaching orb versioning.

2021-05-06 13:55 UTC, closed without merging